#!/bin/sh
set -e
set -x
# Choose location for test executable
e=$(mktemp --tmpdir=${AUTOPKGTEST_TMP} ensmallen-test-XXXXXX)
# Build outside tests to reduce possibility of getting build rather
# than installed ensmallen files via #include.
c++ -O0 -o ${e} tests/*.cpp -lpthread -larmadillo
# cd tests because the executable reads data/* files.
cd tests && ${e} --durations yes
